### ISSUE TITLE
Accept query string in GeocodeRequest

### ISSUE THREAD

**Issue by rjkip** [nozzlegear/nominatim-browser#3]
Hiya Joshua,

Now that the type definitions work, it seems that your GeocodeRequest interface doesn't accept the query string parameter (see http://wiki.openstreetmap.org/wiki/Nominatim#Parameters). Would you accept a PR that adds `q?: string` to said interface?

**Comment by nozzlegear** [comment]
I'd be happy to merge any pull request!

**Comment by nozzlegear** [comment]
I just published 2.0.1 on NPM with this change.
